name: Core API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug
 
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader      

      - name: Unit tests
        run: ./vendor/bin/pest --group=unit

      - name: Feature tests
        run: ./vendor/bin/pest --exclude-group=repository